api_login_check:
  path: /v1/login_check

users:
  type: rest
  host: ~
  prefix: /v1
  resource: App\Controller\UserController
  name_prefix:  api_professeurs_

classes:
  type: rest
  host: ~
  prefix: /v1
  resource: App\Controller\ClasseController
  name_prefix:  api_classes_

qcms:
  type: rest
  host: ~
  prefix: /v1
  resource: App\Controller\QCMController
  name_prefix:  api_qcms_